### Урок 20. Модуль 3. Линейная алгебра

In [1]:
import numpy as np

1. Найти A + B:

 $A=\begin{pmatrix}
1 & 3 & 0\\ 
2 & -4 & 3\\
5 & 6 & 9
\end{pmatrix}$ и $B=\begin{pmatrix}
10 & 6 & -2\\ 
0 & 7 & 4\\
-1 & 2 & 0
\end{pmatrix}$

 $A + B =\begin{pmatrix}
1 & 3 & 0\\ 
2 & -4 & 3\\
5 & 6 & 9
\end{pmatrix}$ +  $\begin{pmatrix}
10 & 6 & -2\\ 
0 & 7 & 4\\
-1 & 2 & 0
\end{pmatrix} = \begin{pmatrix}
11 & 9 & -2\\ 
2 & 3 & 7\\
4 & 8 & 9
\end{pmatrix}$

In [4]:
#проверка
B = np.array([[10, 6, -2], [0, 7, 4], [-1, 2, 0]])
B

array([[10,  6, -2],
       [ 0,  7,  4],
       [-1,  2,  0]])

In [5]:
A = np.array([[1, 3, 0], [2, -4, 3], [5, 6, 9]])
A

array([[ 1,  3,  0],
       [ 2, -4,  3],
       [ 5,  6,  9]])

In [6]:
A + B

array([[11,  9, -2],
       [ 2,  3,  7],
       [ 4,  8,  9]])

Найти A * B:

 $A=\begin{pmatrix}
2 & 8 \\ 
3 & 4
\end{pmatrix}$ и  $B=\begin{pmatrix}
1 & 0 \\ 
4 & 9
\end{pmatrix}$



 $A * B =\begin{pmatrix}
2 & 8 \\ 
3 & 4
\end{pmatrix}$ *  $\begin{pmatrix}
1 & 0 \\ 
4 & 9
\end{pmatrix}$ = $\begin{pmatrix}
2 + 32 & 0 + 72 \\ 
3 + 16 & 0 + 36
\end{pmatrix}$ = $\begin{pmatrix}
34 & 72 \\ 
19 & 36
\end{pmatrix}$

In [8]:
#проверка
A = np.array([[2, 8], [3, 4]])
A

array([[2, 8],
       [3, 4]])

In [9]:
B = np.array([[1, 0], [4, 9]])
B

array([[1, 0],
       [4, 9]])

In [10]:
A @ B

array([[34, 72],
       [19, 36]])

3. Вычислить определители:

$\begin{vmatrix}
3 & 7\\ 
6 & 9
\end{vmatrix}$

$\begin{vmatrix}
4 & 1 & 9\\ 
3 & 2 & 0\\
8 & 7 & 5\\
\end{vmatrix}$

$\begin{vmatrix}
3 & 7\\ 
6 & 9
\end{vmatrix} = 3 * 9 - 7 * 6 = 27 - 42 = - 15$  

In [14]:
#проверка
A = np.array([[3, 7], [6, 9]])
np.linalg.det(A)

-15.0

$\begin{vmatrix}
4 & 1 & 9\\ 
3 & 2 & 0\\
8 & 7 & 5\\
\end{vmatrix} = 4(2*5 - 0*7) - 1(3*5 - 8*0) + 9(3*7 - 2*8) = 40 - 15 + 45 = 70$

In [13]:
#проверка
A = np.array([[4, 1, 9], [3, 2, 0], [8, 7, 5]])
round(np.linalg.det(A))

70