In [30]:
import pandas as pd
import numpy as np

### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

### About Dataset
##### 💸💸💸 Cost of Living - 50k Tweets in English | Aug 2022 💸💸💸

The cost of living is a scorching topic. This dataset is composed of tweets sent from August 20 to August 26 2022, with 50k tweets. All tweets are in English and are from different countries. Below is a breakdown of columns and the data in them.

### О наборе данных
##### 💸💸💸 Стоимость жизни - 50 тысяч твитов на английском языке | август 2022 💸💸💸

Стоимость жизни – животрепещущая тема. Этот набор данных состоит из твитов, отправленных с 20 по 26 августа 2022 года, всего 50 000 твитов. Все твиты на английском и из разных стран. Ниже приведена разбивка столбцов и данных в них.

In [31]:
data = pd.read_csv('dataset/new/costofliving-query-tweets.csv')
data.head()

date_time         username         user_location  \
0  2022-08-26 21:09:51+00:00      CathFordETS   Manchester, England   
1  2022-08-26 21:09:25+00:00       gsvigilant                   NaN   
2  2022-08-26 21:09:19+00:00    Chris07111522                   NaN   
3  2022-08-26 21:09:18+00:00   mnguniomhlophe  Savanna City Midvaal   
4  2022-08-26 21:09:13+00:00  RepAshleyHinson        Washington, DC   

                                    user_description  verified  \
0  Chronic illness advocate. Many health conditio...     False   
1                                                NaN     False   
2  Professional educator, with a curious mind and...     False   
3  Traditional Healer and Clairvoyant: Interested...     False   
4  Proud mom and wife. Representing IA-01 in Cong...      True   

   followers_count  following_count  tweet_like_count  tweet_retweet_count  \
0               20              106                 0                    0   
1                6               29                 0                    0   
2               18               39                 0                    0   
3              431             1603                 0                    0   
4            15667              624                 0                    1   

   tweet_reply_count                                             source  \
0                  0  <a href="http://twitter.com/download/android" ...   
1                  0  <a href="http://twitter.com/download/android" ...   
2                  0  <a href="http://twitter.com/download/android" ...   
3                  0  <a href="https://mobile.twitter.com" rel="nofo...   
4                  0  <a href="http://twitter.com/download/iphone" r...   

                                          tweet_text  
0  @Keir_Starmer Please can you share this petiti...  
1  @amyklobuchar So much for focusing your attent...  
2  @TheLastLeg Kidnap the Tory leadership candida...  
3  I salute all the courageous men and women from...  
4  Unleashing American energy independence is one...

In [32]:
#есть пропуски в столбцах user_location, user_description (заполнять надо на моду, так как это текстовые данные)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50001 entries, 0 to 50000
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   date_time            50001 non-null  object
 1   username             50001 non-null  object
 2   user_location        34297 non-null  object
 3   user_description     42986 non-null  object
 4   verified             50001 non-null  bool  
 5   followers_count      50001 non-null  int64 
 6   following_count      50001 non-null  int64 
 7   tweet_like_count     50001 non-null  int64 
 8   tweet_retweet_count  50001 non-null  int64 
 9   tweet_reply_count    50001 non-null  int64 
 10  source               50001 non-null  object
 11  tweet_text           50001 non-null  object
dtypes: bool(1), int64(5), object(6)
memory usage: 4.2+ MB


In [33]:
#много уникальных
len(data['user_description'].unique())

32018

In [34]:
#много уникальных
len(data['user_location'].unique())

11555

In [35]:
data.shape

(50001, 12)

In [36]:
#средннее значение и медиана не совпадают по многим столбцам, что означает, что есть выбросы.
#по показателям tweet_like_count, tweet_retweet_count, tweet_reply_count - медиана равна нулю, а максимальные значения очень
#большие. То есть есть непопулярные твиты, а есть очень популярные.
data.describe()

followers_count  following_count  tweet_like_count  \
count     5.000100e+04     50001.000000      50001.000000   
mean      4.973863e+04      1737.685126         14.213976   
std       6.771397e+05      6683.105153        373.453878   
min       0.000000e+00         0.000000          0.000000   
25%       9.500000e+01       185.000000          0.000000   
50%       5.380000e+02       620.000000          0.000000   
75%       2.332000e+03      1771.000000          2.000000   
max       2.690649e+07    638937.000000      45979.000000   

       tweet_retweet_count  tweet_reply_count  
count         50001.000000       50001.000000  
mean              3.703086           1.505290  
std             110.519391          22.338956  
min               0.000000           0.000000  
25%               0.000000           0.000000  
50%               0.000000           0.000000  
75%               0.000000           1.000000  
max           14740.000000        2211.000000

In [37]:
data.duplicated().sum()

0

In [38]:
data.isnull().sum()

date_time                  0
username                   0
user_location          15704
user_description        7015
verified                   0
followers_count            0
following_count            0
tweet_like_count           0
tweet_retweet_count        0
tweet_reply_count          0
source                     0
tweet_text                 0
dtype: int64

In [39]:
data.corr()
#tweet_like_count сильно коррелирует с tweet_retweet_count - 0.892648 и tweet_reply_count - 0.671576
#возможно, лайки или ретвиты нужно будет удалить. 

verified  followers_count  following_count  \
verified             1.000000         0.261768         0.058525   
followers_count      0.261768         1.000000         0.027400   
following_count      0.058525         0.027400         1.000000   
tweet_like_count     0.065856         0.020399         0.052773   
tweet_retweet_count  0.060312         0.019235         0.049232   
tweet_reply_count    0.133669         0.073458         0.042920   

                     tweet_like_count  tweet_retweet_count  tweet_reply_count  
verified                     0.065856             0.060312           0.133669  
followers_count              0.020399             0.019235           0.073458  
following_count              0.052773             0.049232           0.042920  
tweet_like_count             1.000000             0.892648           0.671576  
tweet_retweet_count          0.892648             1.000000           0.546457  
tweet_reply_count            0.671576             0.546457           1.000000

In [40]:
data['username'].unique()

array(['CathFordETS', 'gsvigilant', 'Chris07111522', ...,
       'Jonatha67756129', 'MaryTracy', '_Fessial'], dtype=object)

In [41]:
# 37553 из 50001
len(data['username'].unique())

37553

In [42]:
data[data['verified'] == True].head()

date_time         username              user_location  \
4   2022-08-26 21:09:13+00:00  RepAshleyHinson             Washington, DC   
17  2022-08-26 21:07:00+00:00        dailystar                     London   
58  2022-08-26 20:59:49+00:00           BelTel  Belfast, Northern Ireland   
67  2022-08-26 20:58:49+00:00     thecyberwire      Fulton, Maryland, USA   
70  2022-08-26 20:58:43+00:00      LivEchonews              Liverpool, UK   

                                     user_description  verified  \
4   Proud mom and wife. Representing IA-01 in Cong...      True   
17  Home of Fun Stuff! Follow @StarBreaksNews to b...      True   
58  Northern Ireland news, sport, features, opinio...      True   
67  Concise cybersecurity news & analysis for the ...      True   
70  The latest Liverpool news, sport, weather and ...      True   

    followers_count  following_count  tweet_like_count  tweet_retweet_count  \
4             15667              624                 0                    1   
17           227708             3547                 0                    0   
58           219301            14956                 4                    0   
67            39058              884                 0                    0   
70           519641             1392                 3                    0   

    tweet_reply_count                                             source  \
4                   0  <a href="http://twitter.com/download/iphone" r...   
17                  1  <a href="https://about.twitter.com/products/tw...   
58                  0  <a href="https://about.twitter.com/products/tw...   
67                  0  <a href="http://www.hubspot.com/" rel="nofollo...   
70                  1  <a href="https://about.twitter.com/products/tw...   

                                           tweet_text  
4   Unleashing American energy independence is one...  
17  She's travelled to Costa Rica, Thailand and mo...  
58  Margaret Canning: We should feel angry the tim...  
67  Black Basta, Okta on Scatter Swine, Nobelium, ...  
70  A mum-of-12 has given up all hope of ever havi...

In [43]:
# из 50001 3205 - верифицированные
data[data['verified'] == True].shape

(3205, 12)

In [44]:
data[data['followers_count'] > 100][['username', 'user_description', 'followers_count', 'following_count']].head()

username                                   user_description  \
3    mnguniomhlophe  Traditional Healer and Clairvoyant: Interested...   
4   RepAshleyHinson  Proud mom and wife. Representing IA-01 in Cong...   
8        IanHobbs11  My interests are music (Guitar piano and singi...   
10  tasminschofield                                                NaN   
11    paul_draper80                                        #JoinAUnion   

    followers_count  following_count  
3               431             1603  
4             15667              624  
8               102              350  
10              170              438  
11             1475             2778

In [45]:
#создадим столбец id
data.index

RangeIndex(start=0, stop=50001, step=1)

In [46]:
data['id'] = data.index
data.head()

date_time         username         user_location  \
0  2022-08-26 21:09:51+00:00      CathFordETS   Manchester, England   
1  2022-08-26 21:09:25+00:00       gsvigilant                   NaN   
2  2022-08-26 21:09:19+00:00    Chris07111522                   NaN   
3  2022-08-26 21:09:18+00:00   mnguniomhlophe  Savanna City Midvaal   
4  2022-08-26 21:09:13+00:00  RepAshleyHinson        Washington, DC   

                                    user_description  verified  \
0  Chronic illness advocate. Many health conditio...     False   
1                                                NaN     False   
2  Professional educator, with a curious mind and...     False   
3  Traditional Healer and Clairvoyant: Interested...     False   
4  Proud mom and wife. Representing IA-01 in Cong...      True   

   followers_count  following_count  tweet_like_count  tweet_retweet_count  \
0               20              106                 0                    0   
1                6               29                 0                    0   
2               18               39                 0                    0   
3              431             1603                 0                    0   
4            15667              624                 0                    1   

   tweet_reply_count                                             source  \
0                  0  <a href="http://twitter.com/download/android" ...   
1                  0  <a href="http://twitter.com/download/android" ...   
2                  0  <a href="http://twitter.com/download/android" ...   
3                  0  <a href="https://mobile.twitter.com" rel="nofo...   
4                  0  <a href="http://twitter.com/download/iphone" r...   

                                          tweet_text  id  
0  @Keir_Starmer Please can you share this petiti...   0  
1  @amyklobuchar So much for focusing your attent...   1  
2  @TheLastLeg Kidnap the Tory leadership candida...   2  
3  I salute all the courageous men and women from...   3  
4  Unleashing American energy independence is one...   4

In [47]:
cols = list(data.columns.values)
cols 

['date_time',
 'username',
 'user_location',
 'user_description',
 'verified',
 'followers_count',
 'following_count',
 'tweet_like_count',
 'tweet_retweet_count',
 'tweet_reply_count',
 'source',
 'tweet_text',
 'id']

In [48]:
data = data[['id',
 'date_time',
 'username',
 'user_location',
 'user_description',
 'verified',
 'followers_count',
 'following_count',
 'tweet_like_count',
 'tweet_retweet_count',
 'tweet_reply_count',
 'source',
 'tweet_text']]
data.head()

id                  date_time         username         user_location  \
0   0  2022-08-26 21:09:51+00:00      CathFordETS   Manchester, England   
1   1  2022-08-26 21:09:25+00:00       gsvigilant                   NaN   
2   2  2022-08-26 21:09:19+00:00    Chris07111522                   NaN   
3   3  2022-08-26 21:09:18+00:00   mnguniomhlophe  Savanna City Midvaal   
4   4  2022-08-26 21:09:13+00:00  RepAshleyHinson        Washington, DC   

                                    user_description  verified  \
0  Chronic illness advocate. Many health conditio...     False   
1                                                NaN     False   
2  Professional educator, with a curious mind and...     False   
3  Traditional Healer and Clairvoyant: Interested...     False   
4  Proud mom and wife. Representing IA-01 in Cong...      True   

   followers_count  following_count  tweet_like_count  tweet_retweet_count  \
0               20              106                 0                    0   
1                6               29                 0                    0   
2               18               39                 0                    0   
3              431             1603                 0                    0   
4            15667              624                 0                    1   

   tweet_reply_count                                             source  \
0                  0  <a href="http://twitter.com/download/android" ...   
1                  0  <a href="http://twitter.com/download/android" ...   
2                  0  <a href="http://twitter.com/download/android" ...   
3                  0  <a href="https://mobile.twitter.com" rel="nofo...   
4                  0  <a href="http://twitter.com/download/iphone" r...   

                                          tweet_text  
0  @Keir_Starmer Please can you share this petiti...  
1  @amyklobuchar So much for focusing your attent...  
2  @TheLastLeg Kidnap the Tory leadership candida...  
3  I salute all the courageous men and women from...  
4  Unleashing American energy independence is one...

In [49]:
data.groupby(['verified'])['id'].count()

verified
False    46796
True      3205
Name: id, dtype: int64

In [50]:
#заполним пропуски
data.isnull().sum()

id                         0
date_time                  0
username                   0
user_location          15704
user_description        7015
verified                   0
followers_count            0
following_count            0
tweet_like_count           0
tweet_retweet_count        0
tweet_reply_count          0
source                     0
tweet_text                 0
dtype: int64

In [51]:
#user_location          15704
#найдем моду
data['user_location'].mode()

0    London, England
dtype: object

In [52]:
#посчитаем число входений Лондона
data[data['user_location'] == 'London, England']['id'].count()

1147

In [53]:
#заменим на моду
data['user_location'].fillna('London, England', inplace=True)

In [54]:
data.isnull().sum()

id                        0
date_time                 0
username                  0
user_location             0
user_description       7015
verified                  0
followers_count           0
following_count           0
tweet_like_count          0
tweet_retweet_count       0
tweet_reply_count         0
source                    0
tweet_text                0
dtype: int64

In [55]:
#user_description       7015
#найдем моду
data['user_description'].mode()

0    Breaking News, Sports, Entertainment
dtype: object

In [56]:
#посчитаем число входений Breaking News, Sports, Entertainment
data[data['user_description'] == 'Breaking News, Sports, Entertainment']['id'].count()
#мода получается несущественной, так как всего только 101 вхождение. Все же заменим на нее.

101

In [57]:
#заменим на моду
data['user_description'].fillna('Breaking News, Sports, Entertainment', inplace=True)

In [58]:
#пропусков нет
data.isnull().sum()

id                     0
date_time              0
username               0
user_location          0
user_description       0
verified               0
followers_count        0
following_count        0
tweet_like_count       0
tweet_retweet_count    0
tweet_reply_count      0
source                 0
tweet_text             0
dtype: int64

In [59]:
#cгенерируем новый признак  - популярность пользователя. Он будет находиться, как количество подписчиков / количество подписок
data['user_popularity'] = data['followers_count'] / data['following_count']
data.head()

id                  date_time         username         user_location  \
0   0  2022-08-26 21:09:51+00:00      CathFordETS   Manchester, England   
1   1  2022-08-26 21:09:25+00:00       gsvigilant       London, England   
2   2  2022-08-26 21:09:19+00:00    Chris07111522       London, England   
3   3  2022-08-26 21:09:18+00:00   mnguniomhlophe  Savanna City Midvaal   
4   4  2022-08-26 21:09:13+00:00  RepAshleyHinson        Washington, DC   

                                    user_description  verified  \
0  Chronic illness advocate. Many health conditio...     False   
1               Breaking News, Sports, Entertainment     False   
2  Professional educator, with a curious mind and...     False   
3  Traditional Healer and Clairvoyant: Interested...     False   
4  Proud mom and wife. Representing IA-01 in Cong...      True   

   followers_count  following_count  tweet_like_count  tweet_retweet_count  \
0               20              106                 0                    0   
1                6               29                 0                    0   
2               18               39                 0                    0   
3              431             1603                 0                    0   
4            15667              624                 0                    1   

   tweet_reply_count                                             source  \
0                  0  <a href="http://twitter.com/download/android" ...   
1                  0  <a href="http://twitter.com/download/android" ...   
2                  0  <a href="http://twitter.com/download/android" ...   
3                  0  <a href="https://mobile.twitter.com" rel="nofo...   
4                  0  <a href="http://twitter.com/download/iphone" r...   

                                          tweet_text  user_popularity  
0  @Keir_Starmer Please can you share this petiti...         0.188679  
1  @amyklobuchar So much for focusing your attent...         0.206897  
2  @TheLastLeg Kidnap the Tory leadership candida...         0.461538  
3  I salute all the courageous men and women from...         0.268871  
4  Unleashing American energy independence is one...        25.107372

### Numpy

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [62]:
A = np.array([[1, -2, 4], [2, 0, -1]])
B = np.array([[5, 2, 3], [4, 6, 2]])
A, B

(array([[ 1, -2,  4],
        [ 2,  0, -1]]),
 array([[5, 2, 3],
        [4, 6, 2]]))

In [63]:
A + B

array([[6, 0, 7],
       [6, 6, 1]])

In [64]:
A - B

array([[-4, -4,  1],
       [-2, -6, -3]])

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [65]:
A = np.array([[1, 2], [2, -1], [3, 0]])
B = np.array([[-1, 1], [1, 2], [0, 0]])
A, B

(array([[ 1,  2],
        [ 2, -1],
        [ 3,  0]]),
 array([[-1,  1],
        [ 1,  2],
        [ 0,  0]]))

In [66]:
C = A - 3 * B
C

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [67]:
A = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])
A

array([[ 6, -1,  4],
       [ 2,  1, 10],
       [ 8,  0,  2]])

In [69]:
np.linalg.det(A)

-95.99999999999999

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [70]:
A = np.array([[3, 3, -1], [4, 1, 3], [1, -2, -2]])
A

array([[ 3,  3, -1],
       [ 4,  1,  3],
       [ 1, -2, -2]])

In [71]:
B = np.linalg.inv(A)
B

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [72]:
# при умножении матриц получается единичная матрица
A @ B

array([[ 1.00000000e+00, -8.32667268e-17,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])

In [73]:
B @ A

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.77555756e-17,  1.00000000e+00, -1.11022302e-16],
       [-2.77555756e-17, -5.55111512e-17,  1.00000000e+00]])